version: "3.8"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    container_name: SniBot-Engine
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - octobot_user:/octobot/user
      - octobot_tentacles:/octobot/tentacles
      - octobot_logs:/octobot/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

volumes:
  octobot_user:
  octobot_tentacles:
  octobot_logs:
